In [1]:
import pandas as pd
import numpy as np
import os

In [56]:
data = pd.read_csv('/d/shared/users/yyz/penfed/data_3rd_party_refi_f_sent_withunfundedtarget_zestscore_vs4_20250618.csv')

/tmp/ipykernel_1999/815752196.py:1: DtypeWarning: Columns (11,31,52,70,71,80,81,125) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('/d/shared/users/yyz/penfed/data_3rd_party_refi_f_sent_withunfundedtarget_zestscore_vs4_20250618.csv')

In [57]:
data['appmonth'] = data['Application_Date'].str[:7]
data['bookmonth'] = data['Funded_Date'].str[:7]

In [34]:
funded = data[data['Decision'] == 'Funded']

In [37]:
funded_summary = (
    funded.groupby('appmonth')
      .agg(
        total_count       = ('appmonth','size'),
        mob_6_60_notna    = ('mob_6_60',lambda x: x.notna().sum()),
        mob_6_60_eq_1     = ('mob_6_60',lambda x: (x == 1).sum()),
        mob_12_90_notna    = ('mob_12_90',lambda x: x.notna().sum()),
        mob_12_90_eq_1     = ('mob_12_90',lambda x: (x == 1).sum())
      )
      .reset_index()
)

display(funded_summary)

,appmonth,total_count,mob_6_60_notna,mob_6_60_eq_1,mob_12_90_notna,mob_12_90_eq_1
0,2021-01,2556,2556,7,2556,17
1,2021-02,2689,2689,10,2689,21
2,2021-03,3331,3331,17,3331,32
3,2021-04,3098,3098,27,3098,42
4,2021-05,3687,3687,23,3687,50
5,2021-06,5226,5226,42,5226,64
6,2021-07,5001,5001,71,5001,100
7,2021-08,4831,4831,49,4831,110
8,2021-09,5757,5757,93,5757,152
9,2021-10,6119,6119,87,6119,153
10,2021-11,7091,7091,127,7091,240
11,2021-12,7283,7283,144,7283,252
12,2022-01,8078,8078,143,8078,264
13,2022-02,7881,7881,162,7881,278
14,2022-03,9919,9919,227,9919,365
15,2022-04,8710,8710,225,8710,358
16,2022-05,8052,8052,242,8052,343
17,2022-06,7973,7973,188,7973,321
18,2022-07,3157,3157,79,3157,129
19,2022-08,1784,1784,58,1784,85
20,2022-09,1152,1152,20,1152,37
21,2022-10,1650,1650,27,1650,38
22,2022-11,1881,1881,19,1881,50
23,2022-12,2008,2008,18,2008,46
24,2023-01,2417,2417,31,2417,57
25,2023-02,2382,2382,30,2382,55
26,2023-03,3352,3352,37,3352,91
27,2023-04,3336,3336,31,3336,76
28,2023-05,3104,3104,43,3104,84
29,2023-06,2114,2114,14,2114,40
30,2023-07,1372,1372,9,1372,15
31,2023-08,1332,1332,7,1332,15
32,2023-09,1575,1575,8,1575,17
33,2023-10,1596,1596,4,1596,10
34,2023-11,1216,1216,0,1216,9
35,2023-12,1110,1110,6,1110,8
36,2024-01,1504,1504,7,1504,13
37,2024-02,1576,1576,8,1571,11
38,2024-03,1742,1742,4,1448,8
39,2024-04,1534,1534,5,3,0
40,2024-05,905,905,1,0,0
41,2024-06,547,547,0,0,0
42,2024-07,550,550,0,0,0
43,2024-08,489,487,0,0,0
44,2024-09,341,263,0,0,0
45,2024-10,226,1,0,0,0
46,2024-11,214,0,0,0,0
47,2024-12,173,0,0,0,0
48,2025-01,297,0,0,0,0
49,2025-02,283,0,0,0,0
50,2025-03,137,0,0,0,0

In [38]:
funded_summary = (
    funded.groupby('bookmonth')
      .agg(
        total_count       = ('bookmonth','size'),
        mob_6_60_notna    = ('mob_6_60',lambda x: x.notna().sum()),
        mob_6_60_eq_1     = ('mob_6_60',lambda x: (x == 1).sum()),
        mob_12_90_notna    = ('mob_12_90',lambda x: x.notna().sum()),
        mob_12_90_eq_1     = ('mob_12_90',lambda x: (x == 1).sum())
      )
      .reset_index()
)

display(funded_summary)

,bookmonth,total_count,mob_6_60_notna,mob_6_60_eq_1,mob_12_90_notna,mob_12_90_eq_1
0,2020-12,114,114,0,114,0
1,2021-01,2211,2211,7,2211,17
2,2021-02,2657,2657,10,2657,22
3,2021-03,3293,3293,13,3293,26
4,2021-04,3137,3137,24,3137,38
5,2021-05,3659,3659,30,3659,65
6,2021-06,5500,5500,45,5500,71
7,2021-07,4973,4973,73,4973,106
8,2021-08,4959,4959,61,4959,112
9,2021-09,5583,5583,87,5583,141
10,2021-10,6148,6148,80,6148,162
11,2021-11,6942,6942,127,6942,231
12,2021-12,7188,7188,154,7188,260
13,2022-01,8028,8028,132,8028,263
14,2022-02,7679,7679,158,7679,263
15,2022-03,9869,9869,244,9869,368
16,2022-04,8960,8960,211,8960,360
17,2022-05,7852,7852,233,7852,335
18,2022-06,7655,7655,179,7655,301
19,2022-07,3755,3755,87,3755,146
20,2022-08,1947,1947,59,1947,82
21,2022-09,1129,1129,26,1129,40
22,2022-10,1559,1559,22,1559,35
23,2022-11,1806,1806,19,1806,47
24,2022-12,2045,2045,20,2045,40
25,2023-01,2298,2298,25,2298,60
26,2023-02,2391,2391,33,2391,59
27,2023-03,3332,3332,42,3332,90
28,2023-04,3163,3163,29,3163,68
29,2023-05,3278,3278,42,3278,86
30,2023-06,2255,2255,16,2255,51
31,2023-07,1434,1434,9,1434,15
32,2023-08,1324,1324,10,1324,17
33,2023-09,1504,1504,6,1504,13
34,2023-10,1677,1677,3,1677,14
35,2023-11,1192,1192,3,1192,12
36,2023-12,1131,1131,3,1131,5
37,2024-01,1418,1418,9,1418,14
38,2024-02,1573,1573,8,1573,12
39,2024-03,1728,1728,2,1728,9
40,2024-04,1593,1593,6,0,0
41,2024-05,1043,1043,3,0,0
42,2024-06,552,552,0,0,0
43,2024-07,546,546,0,0,0
44,2024-08,516,516,0,0,0
45,2024-09,333,333,0,0,0
46,2024-10,267,0,0,0,0
47,2024-11,219,0,0,0,0
48,2024-12,159,0,0,0,0
49,2025-01,289,0,0,0,0
50,2025-02,287,0,0,0,0
51,2025-03,188,0,0,0,0

In [60]:
proxy_withdraw = data[data['Decision'] == 'Withdraw']

In [40]:
proxy_withdraw_summary = (
    proxy_withdraw.groupby('appmonth')
      .agg(
        total_count       = ('appmonth','size'),
        mob_6_60_notna    = ('mob_6_60',lambda x: x.notna().sum()),
        mob_6_60_eq_1     = ('mob_6_60',lambda x: (x == 1).sum()),
        mob_12_90_notna    = ('mob_12_90',lambda x: x.notna().sum()),
        mob_12_90_eq_1     = ('mob_12_90',lambda x: (x == 1).sum())
      )
      .reset_index()
)

display(proxy_withdraw_summary)

,appmonth,total_count,mob_6_60_notna,mob_6_60_eq_1,mob_12_90_notna,mob_12_90_eq_1
0,2021-01,2283,668,2,668,8
1,2021-02,2497,773,2,773,3
2,2021-03,3096,947,5,947,5
3,2021-04,2908,980,3,980,9
4,2021-05,3296,1088,2,1088,6
5,2021-06,4061,1346,11,1346,26
6,2021-07,4053,1345,10,1345,18
7,2021-08,3893,1247,10,1247,21
8,2021-09,4835,1462,13,1462,24
9,2021-10,5653,1753,19,1753,39
10,2021-11,6095,1759,17,1759,45
11,2021-12,6329,1877,21,1877,39
12,2022-01,7244,2003,25,2003,46
13,2022-02,6554,1922,19,1922,36
14,2022-03,8377,2598,30,2598,53
15,2022-04,7912,2320,27,2320,56
16,2022-05,7477,2170,39,2170,68
17,2022-06,8230,2248,28,2248,58
18,2022-07,4450,1237,13,1237,20
19,2022-08,3566,904,8,904,14
20,2022-09,3588,959,5,959,15
21,2022-10,4086,952,8,952,12
22,2022-11,4027,884,8,884,16
23,2022-12,4620,1057,9,1057,15
24,2023-01,5199,1480,7,1480,14
25,2023-02,5617,1646,7,1646,17
26,2023-03,8407,2550,8,2550,15
27,2023-04,8541,2496,11,2496,22
28,2023-05,7056,1898,8,1898,17
29,2023-06,6277,1546,6,1546,9
30,2023-07,6119,1495,7,1495,15
31,2023-08,6704,1489,2,1489,3
32,2023-09,5445,1412,4,1412,2
33,2023-10,5745,1398,1,1398,3
34,2023-11,5329,1325,1,1324,2
35,2023-12,4879,1168,1,1156,4
36,2024-01,5678,1392,2,1288,3
37,2024-02,6212,1420,3,1130,4
38,2024-03,8482,1961,5,1097,2
39,2024-04,9297,2109,0,473,0
40,2024-05,5939,1379,4,181,0
41,2024-06,3837,805,0,21,0
42,2024-07,3874,795,0,0,0
43,2024-08,3313,556,0,0,0
44,2024-09,3085,335,0,0,0
45,2024-10,1683,39,1,0,0
46,2024-11,1686,6,0,0,0
47,2024-12,1188,0,0,0,0
48,2025-01,2757,0,0,0,0
49,2025-02,3102,0,0,0,0
50,2025-03,3575,0,0,0,0
51,2025-04,5,0,0,0,0

In [61]:
proxy_withdraw_summary = (
    proxy_withdraw.groupby('bookmonth')
      .agg(
        total_count       = ('bookmonth','size'),
        mob_6_60_notna    = ('mob_6_60',lambda x: x.notna().sum()),
        mob_6_60_eq_1     = ('mob_6_60',lambda x: (x == 1).sum()),
        mob_12_90_notna    = ('mob_12_90',lambda x: x.notna().sum()),
        mob_12_90_eq_1     = ('mob_12_90',lambda x: (x == 1).sum())
      )
      .reset_index()
)

display(proxy_withdraw_summary)

,bookmonth,total_count,mob_6_60_notna,mob_6_60_eq_1,mob_12_90_notna,mob_12_90_eq_1
0,2020-12,25,25,0,25,0
1,2021-01,345,345,1,345,4
2,2021-02,535,535,1,535,2
3,2021-03,931,931,3,931,5
4,2021-04,915,915,6,915,10
5,2021-05,1028,1028,2,1028,5
6,2021-06,1253,1253,8,1253,15
7,2021-07,1267,1267,9,1267,21
8,2021-08,1308,1308,7,1308,20
9,2021-09,1392,1392,11,1392,20
10,2021-10,1553,1553,15,1553,37
11,2021-11,1743,1743,14,1743,35
12,2021-12,1698,1698,20,1698,35
13,2022-01,1890,1890,26,1890,49
14,2022-02,1874,1874,24,1874,37
15,2022-03,2517,2517,27,2517,48
16,2022-04,2371,2371,24,2371,46
17,2022-05,2261,2261,23,2261,64
18,2022-06,2306,2306,42,2306,60
19,2022-07,1612,1612,18,1612,42
20,2022-08,1307,1307,15,1307,24
21,2022-09,1038,1038,11,1038,19
22,2022-10,975,975,8,975,12
23,2022-11,943,943,3,943,18
24,2022-12,1029,1029,8,1029,11
25,2023-01,1353,1353,7,1353,15
26,2023-02,1726,1726,12,1726,17
27,2023-03,2195,2195,6,2195,11
28,2023-04,2265,2265,9,2265,21
29,2023-05,2008,2008,9,2008,20
30,2023-06,1807,1807,6,1807,16
31,2023-07,1524,1524,8,1524,15
32,2023-08,1528,1528,6,1528,9
33,2023-09,1522,1522,5,1522,3
34,2023-10,1401,1401,1,1401,2
35,2023-11,1292,1292,1,1292,3
36,2023-12,1146,1146,1,1146,3
37,2024-01,1267,1267,0,1267,3
38,2024-02,1388,1388,4,1359,3
39,2024-03,1691,1691,1,1454,2
40,2024-04,1926,1926,4,388,2
41,2024-05,1627,1627,3,228,0
42,2024-06,1099,1099,1,0,0
43,2024-07,958,958,1,0,0
44,2024-08,809,792,0,0,0
45,2024-09,613,528,1,0,0
46,2024-10,600,31,0,0,0
47,2024-11,475,9,0,0,0
48,2024-12,431,0,0,0,0
49,2025-01,573,0,0,0,0
50,2025-02,679,0,0,0,0
51,2025-03,583,0,0,0,0
52,2025-04,9,0,0,0,0

In [58]:
proxy_decline = data[data['Decision'] == 'Decline']

In [44]:
proxy_decline_summary = (
    proxy_decline.groupby('appmonth')
      .agg(
        total_count       = ('appmonth','size'),
        mob_6_60_notna    = ('mob_6_60',lambda x: x.notna().sum()),
        mob_6_60_eq_1     = ('mob_6_60',lambda x: (x == 1).sum()),
        mob_12_90_notna    = ('mob_12_90',lambda x: x.notna().sum()),
        mob_12_90_eq_1     = ('mob_12_90',lambda x: (x == 1).sum())
      )
      .reset_index()
)

display(proxy_decline_summary)

,appmonth,total_count,mob_6_60_notna,mob_6_60_eq_1,mob_12_90_notna,mob_12_90_eq_1
0,2021-01,1885,754,4,754,8
1,2021-02,2726,1015,15,1015,19
2,2021-03,3289,1094,15,1094,25
3,2021-04,3449,1273,13,1273,32
4,2021-05,3384,1333,20,1333,44
5,2021-06,4138,1670,37,1670,62
6,2021-07,4195,1626,29,1626,54
7,2021-08,4146,1490,36,1490,71
8,2021-09,5130,1802,30,1802,59
9,2021-10,6868,2560,48,2560,87
10,2021-11,7708,2744,54,2744,106
11,2021-12,7765,2824,64,2824,125
12,2022-01,8568,3139,81,3139,140
13,2022-02,8061,2837,94,2837,148
14,2022-03,10339,3526,96,3526,192
15,2022-04,9878,2963,109,2963,176
16,2022-05,9854,3016,99,3016,157
17,2022-06,10393,3019,80,3019,146
18,2022-07,7162,2005,68,2005,100
19,2022-08,4379,1118,27,1118,50
20,2022-09,2792,786,20,786,40
21,2022-10,3217,840,21,840,41
22,2022-11,3350,803,14,803,29
23,2022-12,3156,843,14,843,29
24,2023-01,3936,1138,10,1138,19
25,2023-02,4062,1262,21,1262,46
26,2023-03,5043,1547,25,1547,44
27,2023-04,4996,1448,27,1448,52
28,2023-05,4198,1209,23,1209,35
29,2023-06,3126,851,11,851,22
30,2023-07,2769,876,11,876,24
31,2023-08,3138,900,4,900,19
32,2023-09,3311,924,6,924,12
33,2023-10,4001,1156,9,1156,25
34,2023-11,3043,810,5,810,6
35,2023-12,2919,823,5,819,21
36,2024-01,3572,967,3,909,6
37,2024-02,3585,1071,7,890,9
38,2024-03,4059,1233,11,679,7
39,2024-04,4069,1192,9,207,1
40,2024-05,3522,967,2,78,0
41,2024-06,3209,841,9,8,0
42,2024-07,3492,857,3,0,0
43,2024-08,3348,704,2,0,0
44,2024-09,2970,394,1,0,0
45,2024-10,1198,24,0,0,0
46,2024-11,940,2,0,0,0
47,2024-12,728,0,0,0,0
48,2025-01,1384,0,0,0,0
49,2025-02,1263,0,0,0,0
50,2025-03,1375,0,0,0,0
51,2025-04,1,0,0,0,0

In [59]:
proxy_decline_summary = (
    proxy_decline.groupby('bookmonth')
      .agg(
        total_count       = ('bookmonth','size'),
        mob_6_60_notna    = ('mob_6_60',lambda x: x.notna().sum()),
        mob_6_60_eq_1     = ('mob_6_60',lambda x: (x == 1).sum()),
        mob_12_90_notna    = ('mob_12_90',lambda x: x.notna().sum()),
        mob_12_90_eq_1     = ('mob_12_90',lambda x: (x == 1).sum())
      )
      .reset_index()
)

display(proxy_decline_summary)

,bookmonth,total_count,mob_6_60_notna,mob_6_60_eq_1,mob_12_90_notna,mob_12_90_eq_1
0,2020-12,18,18,0,18,0
1,2021-01,468,468,4,468,6
2,2021-02,709,709,6,709,10
3,2021-03,1061,1061,15,1061,26
4,2021-04,1180,1180,11,1180,26
5,2021-05,1275,1275,19,1275,43
6,2021-06,1658,1658,39,1658,56
7,2021-07,1554,1554,27,1554,54
8,2021-08,1555,1555,27,1555,59
9,2021-09,1788,1788,30,1788,60
10,2021-10,2120,2120,44,2120,79
11,2021-11,2632,2632,39,2632,87
12,2021-12,2766,2766,71,2766,127
13,2022-01,2977,2977,57,2977,110
14,2022-02,2698,2698,91,2698,145
15,2022-03,3328,3328,92,3328,177
16,2022-04,3121,3121,103,3121,165
17,2022-05,2970,2970,105,2970,144
18,2022-06,3008,3008,88,3008,155
19,2022-07,2429,2429,76,2429,145
20,2022-08,1729,1729,51,1729,82
21,2022-09,1099,1099,33,1099,66
22,2022-10,929,929,29,929,46
23,2022-11,769,769,9,769,24
24,2022-12,861,861,11,861,30
25,2023-01,1018,1018,19,1018,32
26,2023-02,1178,1178,10,1178,25
27,2023-03,1509,1509,25,1509,49
28,2023-04,1357,1357,19,1357,42
29,2023-05,1312,1312,28,1312,41
30,2023-06,983,983,18,983,34
31,2023-07,944,944,15,944,28
32,2023-08,952,952,5,952,16
33,2023-09,864,864,6,864,19
34,2023-10,1106,1106,8,1106,14
35,2023-11,858,858,6,858,13
36,2023-12,814,814,5,814,19
37,2024-01,926,926,5,926,13
38,2024-02,1015,1015,6,988,9
39,2024-03,1138,1138,9,970,11
40,2024-04,1207,1207,6,202,1
41,2024-05,1018,1018,4,108,0
42,2024-06,893,893,7,0,0
43,2024-07,897,897,8,0,0
44,2024-08,906,895,3,0,0
45,2024-09,739,645,3,0,0
46,2024-10,589,43,0,0,0
47,2024-11,378,2,0,0,0
48,2024-12,270,0,0,0,0
49,2025-01,344,0,0,0,0
50,2025-02,317,0,0,0,0
51,2025-03,274,0,0,0,0
52,2025-04,4,0,0,0,0